-- Supabase schema untuk Website Piket Kelas
create table if not exists public.piket (
  id bigint generated by default as identity primary key,
  hari text not null,
  nama text not null,
  urutan integer not null default 1,
  created_at timestamptz not null default now()
);

alter table public.piket enable row level security;

-- Sementara untuk tahap awal:
-- siswa boleh membaca data.
create policy "public can read piket"
on public.piket for select
to anon
using (true);

-- JANGAN memberi izin INSERT/UPDATE/DELETE ke anon.
-- Untuk admin, gunakan authentication + policy berbasis user_id
-- setelah akun admin dibuat.
