-- Supabase schema untuk Piket Kelas
create table if not exists public.piket (
  id bigint generated by default as identity primary key,
  tanggal date not null,
  nama text not null,
  status text not null default 'piket' check (status in ('piket','tidak','kabur')),
  urutan integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.piket enable row level security;

-- Publik boleh melihat jadwal.
create policy "Public can view piket"
on public.piket for select
to anon, authenticated
using (true);

-- Untuk produksi, tambahkan policy INSERT/UPDATE/DELETE yang hanya
-- mengizinkan akun admin tertentu (auth.uid()).
-- Jangan pernah menaruh service_role key di index.html.
